### ISSUE TITLE
What config file coffeelint engine use?

### ISSUE THREAD

**Issue by stereodenis** [codeclimate/codeclimate-coffeelint#3]
We have .coffeelint.json config file in our project, but engine don't use it

**Comment by gdiggs** [comment]
@stereodenis If you specify the file in your `.codeclimate.yml` file as shown below, the engine should pick it up!

``` yml
engines:
  coffeelint:
    enabled: true
    config: .coffeelint.json
```

**Comment by stereodenis** [comment]
@GordonDiggs 
not working for me
https://codeclimate.com/repos/5591c20f695680584100ff60/compare/codeclimate-add-new-engines

```
engines:
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
    config: .coffeelint.json
  bundler-audit:
    enabled: true
```
